#!/bin/bash

echo "╔══════════════════════════════════════════════════════════════════════╗"
echo "║              🚀 GitHub Pages 一鍵設定腳本                             ║"
echo "╚══════════════════════════════════════════════════════════════════════╝"
echo ""
echo "此腳本將幫助您完成 GitHub Pages 的設定"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📋 步驟 1: 開啟 GitHub Pages 設定頁面"
echo ""
read -p "按 Enter 在瀏覽器中打開設定頁面..."
$BROWSER "https://github.com/tw092669-ctrl/-Invoice-helper/settings/pages"
echo ""
echo "✅ 請在頁面中："
echo "   1. Source 選擇 'GitHub Actions'"
echo "   2. 點擊 Save"
echo ""
read -p "完成後按 Enter 繼續..."
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📋 步驟 2: 設定 Actions 權限"
echo ""
read -p "按 Enter 在瀏覽器中打開 Actions 設定頁面..."
$BROWSER "https://github.com/tw092669-ctrl/-Invoice-helper/settings/actions"
echo ""
echo "✅ 請在頁面中："
echo "   1. Workflow permissions 選擇 'Read and write permissions'"
echo "   2. 勾選 'Allow GitHub Actions to create and approve pull requests'"
echo "   3. 點擊 Save"
echo ""
read -p "完成後按 Enter 繼續..."
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📋 步驟 3: 設定 API 金鑰"
echo ""
read -p "按 Enter 在瀏覽器中打開 Secrets 設定頁面..."
$BROWSER "https://github.com/tw092669-ctrl/-Invoice-helper/settings/secrets/actions"
echo ""
echo "✅ 請在頁面中："
echo "   1. 點擊 'New repository secret'"
echo "   2. Name: GEMINI_API_KEY"
echo "   3. Value: 輸入您的 Gemini API 金鑰"
echo "   4. 點擊 'Add secret'"
echo ""
read -p "完成後按 Enter 繼續..."
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📋 步驟 4: 推送更新到 GitHub"
echo ""
echo "正在推送..."
git push origin main
echo ""
if [ $? -eq 0 ]; then
    echo "✅ 推送成功！"
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    echo "📋 步驟 5: 查看部署狀態"
    echo ""
    read -p "按 Enter 在瀏覽器中查看部署進度..."
    $BROWSER "https://github.com/tw092669-ctrl/-Invoice-helper/actions"
    echo ""
    echo "🎉 設定完成！"
    echo ""
    echo "等待部署完成後（約 1-2 分鐘），您的網站將可以訪問："
    echo "https://tw092669-ctrl.github.io/-Invoice-helper/"
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    sleep 3
    echo "正在開啟您的網站..."
    $BROWSER "https://tw092669-ctrl.github.io/-Invoice-helper/"
else
    echo "❌ 推送失敗，請檢查錯誤訊息"
fi
